services:
  db-mysql:
    image: mysql:8.0
    container_name: techstudies-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - api-network

  techstudies-api:
    build: .
    container_name: techstudies-api-app
    restart: on-failure
    depends_on:
      db-mysql:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/${MYSQL_DB}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASS}
      - API_SECURITY_TOKEN=${API_SECURITY_TOKEN}
      - APP_PORT=8080
    networks:
      - api-network

networks:
  api-network:
    driver: bridge

volumes:
  db_data: